// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKE0_7gIqXvXrF14MUIIJ75CqznLqvqdw',
    appId: '1:611243802394:web:f6391546401a773cd3f6a3',
    messagingSenderId: '611243802394',
    projectId: 'colorselect-ai',
    authDomain: 'colorselect-ai.firebaseapp.com',
    storageBucket: 'colorselect-ai.firebasestorage.app',
    measurementId: 'G-35609HW5B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoLDNZwba4yztNj3637MO1hYG-SXFmoM8',
    appId: '1:611243802394:android:50e9e4954dd6564ad3f6a3',
    messagingSenderId: '611243802394',
    projectId: 'colorselect-ai',
    storageBucket: 'colorselect-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0CWxeox0pC1IuN9qWpAPUDaVzhCOO9qI',
    appId: '1:611243802394:ios:96ce719dee9e53fbd3f6a3',
    messagingSenderId: '611243802394',
    projectId: 'colorselect-ai',
    storageBucket: 'colorselect-ai.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0CWxeox0pC1IuN9qWpAPUDaVzhCOO9qI',
    appId: '1:611243802394:ios:96ce719dee9e53fbd3f6a3',
    messagingSenderId: '611243802394',
    projectId: 'colorselect-ai',
    storageBucket: 'colorselect-ai.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKE0_7gIqXvXrF14MUIIJ75CqznLqvqdw',
    appId: '1:611243802394:web:687dec73d23531a3d3f6a3',
    messagingSenderId: '611243802394',
    projectId: 'colorselect-ai',
    authDomain: 'colorselect-ai.firebaseapp.com',
    storageBucket: 'colorselect-ai.firebasestorage.app',
    measurementId: 'G-8GNES3WCR5',
  );
}
